(module
  (import "console" "log" (func $print (param i32)))
  (func $fib (export "fib") (param $n i32) (result i32)
    (block
      (local.get $n)
      (i32.const 2)
      (i32.lt_s)
      (i32.eqz)
      (br_if 0)
      (local.get $n)
      (return)
    )
    (local.get $n)
    (i32.const 1)
    (i32.sub)
    (call $fib)
    (local.get $n)
    (i32.const 2)
    (i32.sub)
    (call $fib)
    (i32.add)
    (return)
  (unreachable)
  )
)
